name: "Jira Issue Key Checker"
description: "Checks If a PR contains its linked Jira issue key in both the title and the description."
branding:
  icon: "tag"
  color: "purple"
on: [pull_request]
inputs:
  GITHUB_TOKEN:
    required: true
  project-prefix:
    required: true
    description: "Jira project key prefix. Ex. ABC-1111, prefix would be ABC"
  project-pr:
    required: true
    description: "PR title to be merged"
runs:
  using: "node12"
  main: "index.js"
