# This is a basic workflow to help you get started with Actions

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

name: Test Find Issue Key

jobs:
  test-find-issue-key:
    name: Find Issue Key
    runs-on: ubuntu-latest
    steps:

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find Issue Key
      id: find
      uses: atlassian/gajira-find-issue-key@master
      with:
        from: ${{ github.event.pull_request.head.ref }}

    - name: Verify issue info
      id: Check
      uses: onesliq/jira-actions@master
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          project-prefix: 'PROJECT'
          project-pr: ${{ steps.find.outputs.issue }}
